version: '3'
services:
  app:
    build: ./talescape-backend  # المجلد الذي يحتوي على Dockerfile الخاص بتطبيقك
    ports:
      - "3000:3000"  # تأكد من مطابقة المنفذ مع المنفذ الذي يستخدمه تطبيقك
    volumes:
      - ./talescape-backend:/usr/src/app  # ربط المجلدات لتحديث الكود مباشرة
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example  # كلمة مرور الجذر
      MYSQL_DATABASE: talescape     # اسم قاعدة البيانات
    ports:
      - "3306:3306"  # المنفذ الذي يستخدمه MySQL
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_ROOT_PASSWORD: example  # نفس كلمة المرور الخاصة بقاعدة البيانات
    ports:
      - "8080:80"  # الوصول إلى phpMyAdmin عبر المنفذ 8080

volumes:
  db-data:
